language: node_js
node_js:
  - "10"

install:
  - yarn install

script:
  - yarn run build

before_deploy:
  - cd build/clapp-player/win64
  - zip -r ../clapp-player-win64 *

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN_ACCESS
  file: "../clapp-player-win64.zip"
  skip_cleanup: true
  on:
    tags: true