language: node_js
node_js:
  - "10"

script:
  - yarn run build

before_deploy:
  - zip -j clapp-player bin/*

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN_ACCESS
  file: "clapp-player.zip"
  skip_cleanup: true