language: node_js
node_js:
  - "10"

install:
  - yarn install

script:
  - yarn run build

before_deploy:
  - cd build/clapp-player/
  - zip -r ../../clapp-player *
  - pwd
  - ls ../..

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN_ACCESS
  file: "clapp-player.zip"
  skip_cleanup: true
  # on:
  #   tags: true